# Mode of operation: ASTRA, CASSANDRA, FILE
#mode = "ASTRA"
#mode = "CASSANDRA"
mode = "FILE"


# Cassandra connection
cassandra_host = "127.0.0.1"
cassandra_port = 9042
keyspace = "killrvideo"

# Schema file
schema_file = "test/schema/killrvideo-schema.cql"

# Logging 
log_level = "INFO"

# LLM provider info: AZURE, VERTEXAI, BEDROCK, OLLAMA, OPENAI
#llm_provider = "OPENAI"
#llm_provider = "BEDROCK"
llm_provider = "VERTEXAI"

# Azure GPT

# GCP VertexAI (You'll need to use the glcoud CLI to authenticate)
vertexai_model_name = "vertex_ai/gemini-pro"
vertexai_location = "us-central1"

# AWS Bedrock
aws_bedrock_model_name = "bedrock/anthropic.claude-instant-v1"
aws_bedrock_max_tokens = 500
aws_bedrock_temperature = 0.7

# Ollama

# OpenAI
openai_model_system_role = "You are an Apache Cassandra expert at data modeling and Generative AI strategy."
openai_model = "gpt-4-turbo-preview"