# Mode of operation: ASTRA, CASSANDRA, FILE
#mode = "ASTRA"
mode = "CASSANDRA"
#mode = "FILE"


# Cassandra connection
cassandra_host = "127.0.0.1"
cassandra_port = 9042
keyspace = "killrvideo"

# Schema file
schema_directory = "test/schema"

# Logging 
log_level = "INFO"

# OpenAI
model_system_role = "You are an Apache Cassandra expert at data modeling and Generative AI strategy."
openai_model = "gpt-4-turbo-preview"